# Generated by Django 5.0.7 on 2024-07-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_room_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='location',
            field=models.TextField(),
        ),
    ]
